name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      # --- INICIO DE LA NUEVA SECCIÓN DE COMPILACIÓN MANUAL ---
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies and Build
        run: |
          cd frontend/clickyfest-app
          npm install
          npm run build -- --configuration production
      # --- FIN DE LA NUEVA SECCIÓN ---

      - name: Deploy to Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_GLACIER_03DF13E0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # ¡OJO A ESTE CAMBIO! Ahora le pasamos la carpeta ya compilada.
          app_location: "frontend/clickyfest-app/dist/clickyfest-app" 
          api_location: "" 
          output_location: "" # Ya no es necesario, lo especificamos en app_location
          
  close_pull_request_job:
    # ... (esta parte no cambia)